"""add_chat_sessions

Revision ID: 218a5abda747
Revises: 8d90cbe925e5
Create Date: 2026-06-09 19:12:01.676578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '218a5abda747'
down_revision: Union[str, Sequence[str], None] = '8d90cbe925e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index('ix_chat_sessions_user_id_updated_at', 'chat_sessions', ['user_id', 'updated_at'], unique=False)
    op.add_column('chat_histories', sa.Column('chat_session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_histories_chat_session_id'), 'chat_histories', ['chat_session_id'], unique=False)
    op.create_foreign_key(None, 'chat_histories', 'chat_sessions', ['chat_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_histories', type_='foreignkey')
    op.drop_index(op.f('ix_chat_histories_chat_session_id'), table_name='chat_histories')
    op.drop_column('chat_histories', 'chat_session_id')
    op.drop_index('ix_chat_sessions_user_id_updated_at', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
