"""add dashboard telemetry indexes

Revision ID: ade129f0dc46
Revises: 1f6823b1c6f0
Create Date: 2026-06-11 08:00:36.536772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ade129f0dc46'
down_revision: Union[str, Sequence[str], None] = '1f6823b1c6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_iot_nodes_active_mission_id', 'iot_nodes', ['mission_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_missions_active_owner_id', 'missions', ['owner_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_telemetry_active_environment_timestamp_node', 'telemetry', ['timestamp', 'iot_node_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND (temperature_celsius IS NOT NULL OR humidity_percent IS NOT NULL)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_active_environment_timestamp_node', table_name='telemetry', postgresql_where=sa.text('deleted_at IS NULL AND (temperature_celsius IS NOT NULL OR humidity_percent IS NOT NULL)'))
    op.drop_index('ix_missions_active_owner_id', table_name='missions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_iot_nodes_active_mission_id', table_name='iot_nodes', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
