"""add_admin_cost_management

Revision ID: b20b64c51624
Revises: cbff3186128e
Create Date: 2026-06-24 21:12:52.053145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b20b64c51624'
down_revision: Union[str, Sequence[str], None] = 'cbff3186128e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_budget_usd', sa.Float(), nullable=False),
    sa.Column('alert_threshold_percent', sa.Integer(), nullable=False),
    sa.CheckConstraint('alert_threshold_percent BETWEEN 1 AND 100', name='ck_cost_budgets_alert_threshold'),
    sa.CheckConstraint('monthly_budget_usd >= 0', name='ck_cost_budgets_monthly'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_session_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('usage_metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cost_usd >= 0', name='ck_llm_usage_cost_usd'),
    sa.CheckConstraint('input_tokens >= 0', name='ck_llm_usage_input_tokens'),
    sa.CheckConstraint('output_tokens >= 0', name='ck_llm_usage_output_tokens'),
    sa.CheckConstraint('total_tokens >= 0', name='ck_llm_usage_total_tokens'),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_usage_active_occurred_at', 'llm_usage_events', ['occurred_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_llm_usage_events_chat_session_id'), 'llm_usage_events', ['chat_session_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_events_user_id'), 'llm_usage_events', ['user_id'], unique=False)
    op.create_index('ix_llm_usage_occurred_at', 'llm_usage_events', ['occurred_at'], unique=False)
    op.create_index('ix_llm_usage_run_id', 'llm_usage_events', ['run_id'], unique=False)
    op.create_index('ix_llm_usage_user_occurred_at', 'llm_usage_events', ['user_id', 'occurred_at'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(), server_default='operator', nullable=False))
    op.create_check_constraint('ck_users_role', 'users', "role IN ('operator', 'admin')")
    op.alter_column('users', 'role', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_role', 'users', type_='check')
    op.drop_column('users', 'role')
    op.drop_index('ix_llm_usage_user_occurred_at', table_name='llm_usage_events')
    op.drop_index('ix_llm_usage_run_id', table_name='llm_usage_events')
    op.drop_index('ix_llm_usage_occurred_at', table_name='llm_usage_events')
    op.drop_index(op.f('ix_llm_usage_events_user_id'), table_name='llm_usage_events')
    op.drop_index(op.f('ix_llm_usage_events_chat_session_id'), table_name='llm_usage_events')
    op.drop_index('ix_llm_usage_active_occurred_at', table_name='llm_usage_events', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('llm_usage_events')
    op.drop_table('cost_budgets')
    # ### end Alembic commands ###
