"""add_iot_node_api_key_hash

Revision ID: cbff3186128e
Revises: ade129f0dc46
Create Date: 2026-06-18 22:43:29.305440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cbff3186128e'
down_revision: Union[str, Sequence[str], None] = 'ade129f0dc46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iot_nodes', sa.Column('api_key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iot_nodes', 'api_key_hash')
    # ### end Alembic commands ###
