apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: c2-app
  labels:
    app.kubernetes.io/name: frontend
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
